# Node.js 기본 이미지
FROM node:20

# 작업 디렉토리 생성
WORKDIR /usr/src/app

# package.json과 tsconfig.json 복사
COPY package*.json tsconfig.json ./

# 의존성 설치
RUN npm install

# 소스 코드 복사
COPY ./src ./src

# TypeScript 빌드 실행
RUN npm run build

# 컨테이너 포트 노출
EXPOSE 3000

# 애플리케이션 시작
CMD ["npm", "start"]
